<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Subscribe</name>
   <tag></tag>
   <elementGuidId>a84630a0-298e-4855-b85f-8451db24eb21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;upgrade-modal&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body widget&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4 col-sm-6 ng-scope&quot;]/div[@class=&quot;pricing pricing-mini text-center&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;pricing-buttons&quot;]/button[@class=&quot;btn btn-block btn-primary&quot;][count(. | //button[(text() = 'Subscribe' or . = 'Subscribe')]) = count(//button[(text() = 'Subscribe' or . = 'Subscribe')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-block btn-primary</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>modal</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#nopayment-modal</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-show</name>
      <type>Main</type>
      <value>(mpc.merchantLastPackageTransaction.BasicPackage.ID !== package.ID || (((mpc.merchantStatus === 1 &amp;&amp; mpc.subscriptionStatus === 0) || mpc.merchantStatus !== 1) &amp;&amp; mpc.merchantLastPackageTransaction.BasicPackage.ID === package.ID)) &amp;&amp; !mpc.cardExist</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Subscribe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;upgrade-modal&quot;)/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body widget&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4 col-sm-6 ng-scope&quot;]/div[@class=&quot;pricing pricing-mini text-center&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;pricing-buttons&quot;]/button[@class=&quot;btn btn-block btn-primary&quot;]</value>
   </webElementProperties>
</WebElementEntity>
