<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>k.button_Register</name>
   <tag></tag>
   <elementGuidId>52f82d4a-a3c3-4886-b1c8-7d6c579556ce</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-darkblue-1 btn-block</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>mrc.onSignUp()</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>mrc.saveFlag</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Register</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;fixed-left signup-page ng-scope&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;full-content-center&quot;]/div[@class=&quot;row margin-bottom-lg&quot;]/div[@class=&quot;col-md-7&quot;]/div[@class=&quot;signup-wrap animated fadeInUp&quot;]/div[@class=&quot;login-block&quot;]/div[@class=&quot;signup-input row&quot;]/div[@class=&quot;col-md-12 col-sm-12 margin-top-sm&quot;]/div[@class=&quot;form-group signup-input&quot;]/button[@class=&quot;btn btn-darkblue-1 btn-block&quot;]</value>
   </webElementProperties>
</WebElementEntity>
